"""
report.py — Night Cycle run report.

Captures the output of a night cycle run: which tasks ran, what they
produced, timing, errors, and any proposals requiring DA review.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass
class Proposal:
    """A single actionable proposal generated by a night-cycle task."""

    proposal_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    task: str = ""
    domain_id: str = ""
    proposal_type: str = ""          # e.g. "glossary_add", "glossary_prune", "inconsistency"
    summary: str = ""
    detail: dict[str, Any] = field(default_factory=dict)
    status: str = "pending"          # pending | approved | rejected

    def to_dict(self) -> dict[str, Any]:
        return {
            "proposal_id": self.proposal_id,
            "task": self.task,
            "domain_id": self.domain_id,
            "proposal_type": self.proposal_type,
            "summary": self.summary,
            "detail": self.detail,
            "status": self.status,
        }


@dataclass
class TaskResult:
    """Result of a single night-cycle task execution."""

    task: str = ""
    domain_id: str = ""
    success: bool = True
    duration_seconds: float = 0.0
    error: str | None = None
    proposals: list[Proposal] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "task": self.task,
            "domain_id": self.domain_id,
            "success": self.success,
            "duration_seconds": self.duration_seconds,
            "error": self.error,
            "proposals": [p.to_dict() for p in self.proposals],
            "metadata": self.metadata,
        }


@dataclass
class NightCycleReport:
    """Aggregate report for a complete night cycle run."""

    run_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    started_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    finished_at: str | None = None
    triggered_by: str = "scheduler"   # "scheduler" | actor_id
    status: str = "running"           # running | completed | failed | cancelled
    task_results: list[TaskResult] = field(default_factory=list)
    total_proposals: int = 0

    def finish(self) -> None:
        self.finished_at = datetime.now(timezone.utc).isoformat()
        self.status = "completed" if all(r.success for r in self.task_results) else "failed"
        self.total_proposals = sum(len(r.proposals) for r in self.task_results)

    def to_dict(self) -> dict[str, Any]:
        return {
            "run_id": self.run_id,
            "started_at": self.started_at,
            "finished_at": self.finished_at,
            "triggered_by": self.triggered_by,
            "status": self.status,
            "task_results": [r.to_dict() for r in self.task_results],
            "total_proposals": self.total_proposals,
        }
